# Generated by Django 3.1.6 on 2021-02-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ghar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('floors', models.IntegerField()),
                ('location', models.CharField(max_length=80)),
                ('owner', models.CharField(max_length=60)),
            ],
        ),
    ]
